(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RingCentralApi) {
      root.RingCentralApi = {};
    }
    root.RingCentralApi.Body2 = factory(root.RingCentralApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Body2 model module.
   * @module model/Body2
   * @version v1.0
   */

  /**
   * Constructs a new <code>Body2</code>.
   * @alias module:model/Body2
   * @class
   */
  var exports = function() {









  };

  /**
   * Constructs a <code>Body2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body2} obj Optional instance to populate.
   * @return {module:model/Body2} The populated <code>Body2</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) { 
      obj = obj || new exports();

      if (data.hasOwnProperty('grant_type')) {
        obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
      }
      if (data.hasOwnProperty('access_token_ttl')) {
        obj['access_token_ttl'] = ApiClient.convertToType(data['access_token_ttl'], 'Integer');
      }
      if (data.hasOwnProperty('refresh_token_ttl')) {
        obj['refresh_token_ttl'] = ApiClient.convertToType(data['refresh_token_ttl'], 'Integer');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('extension')) {
        obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('endpoint_id')) {
        obj['endpoint_id'] = ApiClient.convertToType(data['endpoint_id'], 'String');
      }
    }
    return obj;
  }


  /**
   * Must hold password value for Resource Owner Credentials flow. If client application is not authorized by the specified grant_type, response does not contain refresh_token and refresh_token_ttl attributes
   * @member {String} grant_type
   */
  exports.prototype['grant_type'] = undefined;

  /**
   * Optional. Access token lifetime in seconds; the possible values are from 600 sec (10 min) to 3600 sec (1 hour). The default value is 3600 sec. If the value specified exceeds the default one, the default value is set. If the value specified is less than 600 seconds, the minimum value (600 sec) is set
   * @member {Integer} access_token_ttl
   */
  exports.prototype['access_token_ttl'] = undefined;

  /**
   * Optional. Refresh token lifetime in seconds. The default value depends on the client application, but as usual it equals to 7 days. If the value specified exceeds the default one, the default value is applied. If client specifies refresh_token_ttl<=0, refresh token is not returned even if the corresponding grant type is supported
   * @member {Integer} refresh_token_ttl
   */
  exports.prototype['refresh_token_ttl'] = undefined;

  /**
   * Phone number linked to account or extension in account in E.164 format with or without leading \"+\" sign
   * @member {String} username
   */
  exports.prototype['username'] = undefined;

  /**
   * Optional. Extension short number. If company number is specified as a username, and extension is not specified, the server will attempt to authenticate client as main company administrator
   * @member {String} extension
   */
  exports.prototype['extension'] = undefined;

  /**
   * User's password
   * @member {String} password
   */
  exports.prototype['password'] = undefined;

  /**
   * Optional. List of API permissions to be used with access token (see Application Permissions). Can be omitted when requesting all permissions defined during the application registration phase
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;

  /**
   * Optional. Unique identifier of a client application. You can pass it in request according to pattern [a-zA-Z0-9_\\-]{1,64}. Otherwise it is auto-generated by server. The value will be returned in response in both cases
   * @member {String} endpoint_id
   */
  exports.prototype['endpoint_id'] = undefined;




  return exports;
}));
