using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountInfoTests
    {
        private AccountInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of AccountInfo
        /// </summary>
        [Test]
        public void AccountInfoInstanceTest()
        {
            Assert.IsInstanceOf<AccountInfo> (instance, "instance is a AccountInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'MainNumber' 
        /// </summary>
        [Test]
        public void MainNumberTest()
        {
            // TODO: unit test for the property 'MainNumber' 
        }
        
        /// <summary>
        /// Test the property '_Operator' 
        /// </summary>
        [Test]
        public void _OperatorTest()
        {
            // TODO: unit test for the property '_Operator' 
        }
        
        /// <summary>
        /// Test the property 'PartnerId' 
        /// </summary>
        [Test]
        public void PartnerIdTest()
        {
            // TODO: unit test for the property 'PartnerId' 
        }
        
        /// <summary>
        /// Test the property 'ServiceInfo' 
        /// </summary>
        [Test]
        public void ServiceInfoTest()
        {
            // TODO: unit test for the property 'ServiceInfo' 
        }
        
        /// <summary>
        /// Test the property 'SetupWizardState' 
        /// </summary>
        [Test]
        public void SetupWizardStateTest()
        {
            // TODO: unit test for the property 'SetupWizardState' 
        }
        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'StatusInfo' 
        /// </summary>
        [Test]
        public void StatusInfoTest()
        {
            // TODO: unit test for the property 'StatusInfo' 
        }
        

    }

}
