using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnsweringRuleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnsweringRuleInfoTests
    {
        private AnsweringRuleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnsweringRuleInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of AnsweringRuleInfo
        /// </summary>
        [Test]
        public void AnsweringRuleInfoInstanceTest()
        {
            Assert.IsInstanceOf<AnsweringRuleInfo> (instance, "instance is a AnsweringRuleInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'Enabled' 
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO: unit test for the property 'Enabled' 
        }
        
        /// <summary>
        /// Test the property 'Schedule' 
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO: unit test for the property 'Schedule' 
        }
        
        /// <summary>
        /// Test the property 'CalledNumbers' 
        /// </summary>
        [Test]
        public void CalledNumbersTest()
        {
            // TODO: unit test for the property 'CalledNumbers' 
        }
        
        /// <summary>
        /// Test the property 'Callers' 
        /// </summary>
        [Test]
        public void CallersTest()
        {
            // TODO: unit test for the property 'Callers' 
        }
        
        /// <summary>
        /// Test the property 'CallHandlingAction' 
        /// </summary>
        [Test]
        public void CallHandlingActionTest()
        {
            // TODO: unit test for the property 'CallHandlingAction' 
        }
        
        /// <summary>
        /// Test the property 'Forwarding' 
        /// </summary>
        [Test]
        public void ForwardingTest()
        {
            // TODO: unit test for the property 'Forwarding' 
        }
        
        /// <summary>
        /// Test the property 'UnconditionalForwarding' 
        /// </summary>
        [Test]
        public void UnconditionalForwardingTest()
        {
            // TODO: unit test for the property 'UnconditionalForwarding' 
        }
        
        /// <summary>
        /// Test the property 'Voicemail' 
        /// </summary>
        [Test]
        public void VoicemailTest()
        {
            // TODO: unit test for the property 'Voicemail' 
        }
        

    }

}
