using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnsweringRuleInfoCallerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnsweringRuleInfoCallerInfoTests
    {
        private AnsweringRuleInfoCallerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnsweringRuleInfoCallerInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of AnsweringRuleInfoCallerInfo
        /// </summary>
        [Test]
        public void AnsweringRuleInfoCallerInfoInstanceTest()
        {
            Assert.IsInstanceOf<AnsweringRuleInfoCallerInfo> (instance, "instance is a AnsweringRuleInfoCallerInfo");
        }

        
        /// <summary>
        /// Test the property 'CallerId' 
        /// </summary>
        [Test]
        public void CallerIdTest()
        {
            // TODO: unit test for the property 'CallerId' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        

    }

}
