using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body2Tests
    {
        private Body2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body2();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body2
        /// </summary>
        [Test]
        public void Body2InstanceTest()
        {
            Assert.IsInstanceOf<Body2> (instance, "instance is a Body2");
        }

        
        /// <summary>
        /// Test the property 'GrantType' 
        /// </summary>
        [Test]
        public void GrantTypeTest()
        {
            // TODO: unit test for the property 'GrantType' 
        }
        
        /// <summary>
        /// Test the property 'AccessTokenTtl' 
        /// </summary>
        [Test]
        public void AccessTokenTtlTest()
        {
            // TODO: unit test for the property 'AccessTokenTtl' 
        }
        
        /// <summary>
        /// Test the property 'RefreshTokenTtl' 
        /// </summary>
        [Test]
        public void RefreshTokenTtlTest()
        {
            // TODO: unit test for the property 'RefreshTokenTtl' 
        }
        
        /// <summary>
        /// Test the property 'Username' 
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO: unit test for the property 'Username' 
        }
        
        /// <summary>
        /// Test the property 'Extension' 
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO: unit test for the property 'Extension' 
        }
        
        /// <summary>
        /// Test the property 'Password' 
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO: unit test for the property 'Password' 
        }
        
        /// <summary>
        /// Test the property 'Scope' 
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO: unit test for the property 'Scope' 
        }
        
        /// <summary>
        /// Test the property 'EndpointId' 
        /// </summary>
        [Test]
        public void EndpointIdTest()
        {
            // TODO: unit test for the property 'EndpointId' 
        }
        

    }

}
