using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body9
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body9Tests
    {
        private Body9 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body9();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body9
        /// </summary>
        [Test]
        public void Body9InstanceTest()
        {
            Assert.IsInstanceOf<Body9> (instance, "instance is a Body9");
        }

        
        /// <summary>
        /// Test the property 'EventFilters' 
        /// </summary>
        [Test]
        public void EventFiltersTest()
        {
            // TODO: unit test for the property 'EventFilters' 
        }
        

    }

}
