using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body4
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body4Tests
    {
        private Body4 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body4();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body4
        /// </summary>
        [Test]
        public void Body4InstanceTest()
        {
            Assert.IsInstanceOf<Body4> (instance, "instance is a Body4");
        }

        
        /// <summary>
        /// Test the property 'To' 
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO: unit test for the property 'To' 
        }
        
        /// <summary>
        /// Test the property 'Resolution' 
        /// </summary>
        [Test]
        public void ResolutionTest()
        {
            // TODO: unit test for the property 'Resolution' 
        }
        
        /// <summary>
        /// Test the property 'SendTime' 
        /// </summary>
        [Test]
        public void SendTimeTest()
        {
            // TODO: unit test for the property 'SendTime' 
        }
        
        /// <summary>
        /// Test the property 'CoverIndex' 
        /// </summary>
        [Test]
        public void CoverIndexTest()
        {
            // TODO: unit test for the property 'CoverIndex' 
        }
        
        /// <summary>
        /// Test the property 'CoverPageText' 
        /// </summary>
        [Test]
        public void CoverPageTextTest()
        {
            // TODO: unit test for the property 'CoverPageText' 
        }
        
        /// <summary>
        /// Test the property 'OriginalMessageId' 
        /// </summary>
        [Test]
        public void OriginalMessageIdTest()
        {
            // TODO: unit test for the property 'OriginalMessageId' 
        }
        

    }

}
