using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BodyTests
    {
        private Body instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body
        /// </summary>
        [Test]
        public void BodyInstanceTest()
        {
            Assert.IsInstanceOf<Body> (instance, "instance is a Body");
        }

        
        /// <summary>
        /// Test the property 'ResponseType' 
        /// </summary>
        [Test]
        public void ResponseTypeTest()
        {
            // TODO: unit test for the property 'ResponseType' 
        }
        
        /// <summary>
        /// Test the property 'ClientId' 
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO: unit test for the property 'ClientId' 
        }
        
        /// <summary>
        /// Test the property 'RedirectUri' 
        /// </summary>
        [Test]
        public void RedirectUriTest()
        {
            // TODO: unit test for the property 'RedirectUri' 
        }
        
        /// <summary>
        /// Test the property 'State' 
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO: unit test for the property 'State' 
        }
        

    }

}
