using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body1Tests
    {
        private Body1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body1();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body1
        /// </summary>
        [Test]
        public void Body1InstanceTest()
        {
            Assert.IsInstanceOf<Body1> (instance, "instance is a Body1");
        }

        
        /// <summary>
        /// Test the property 'Token' 
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO: unit test for the property 'Token' 
        }
        

    }

}
