using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body8
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body8Tests
    {
        private Body8 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Body8();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Body8
        /// </summary>
        [Test]
        public void Body8InstanceTest()
        {
            Assert.IsInstanceOf<Body8> (instance, "instance is a Body8");
        }

        
        /// <summary>
        /// Test the property 'EventFilters' 
        /// </summary>
        [Test]
        public void EventFiltersTest()
        {
            // TODO: unit test for the property 'EventFilters' 
        }
        
        /// <summary>
        /// Test the property 'DeliveryMode' 
        /// </summary>
        [Test]
        public void DeliveryModeTest()
        {
            // TODO: unit test for the property 'DeliveryMode' 
        }
        

    }

}
