using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BusinessHourScheduleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BusinessHourScheduleInfoTests
    {
        private BusinessHourScheduleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BusinessHourScheduleInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of BusinessHourScheduleInfo
        /// </summary>
        [Test]
        public void BusinessHourScheduleInfoInstanceTest()
        {
            Assert.IsInstanceOf<BusinessHourScheduleInfo> (instance, "instance is a BusinessHourScheduleInfo");
        }

        
        /// <summary>
        /// Test the property 'WeeklyRanges' 
        /// </summary>
        [Test]
        public void WeeklyRangesTest()
        {
            // TODO: unit test for the property 'WeeklyRanges' 
        }
        

    }

}
