using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallerInfoTests
    {
        private CallerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CallerInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of CallerInfo
        /// </summary>
        [Test]
        public void CallerInfoInstanceTest()
        {
            Assert.IsInstanceOf<CallerInfo> (instance, "instance is a CallerInfo");
        }

        
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        
        /// <summary>
        /// Test the property 'ExtensionNumber' 
        /// </summary>
        [Test]
        public void ExtensionNumberTest()
        {
            // TODO: unit test for the property 'ExtensionNumber' 
        }
        
        /// <summary>
        /// Test the property 'Location' 
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO: unit test for the property 'Location' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        

    }

}
