using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConferencingInfoPhoneNumberInfoCountryInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConferencingInfoPhoneNumberInfoCountryInfoTests
    {
        private ConferencingInfoPhoneNumberInfoCountryInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConferencingInfoPhoneNumberInfoCountryInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ConferencingInfoPhoneNumberInfoCountryInfo
        /// </summary>
        [Test]
        public void ConferencingInfoPhoneNumberInfoCountryInfoInstanceTest()
        {
            Assert.IsInstanceOf<ConferencingInfoPhoneNumberInfoCountryInfo> (instance, "instance is a ConferencingInfoPhoneNumberInfoCountryInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'CallingCode' 
        /// </summary>
        [Test]
        public void CallingCodeTest()
        {
            // TODO: unit test for the property 'CallingCode' 
        }
        
        /// <summary>
        /// Test the property 'EmergencyCalling' 
        /// </summary>
        [Test]
        public void EmergencyCallingTest()
        {
            // TODO: unit test for the property 'EmergencyCalling' 
        }
        
        /// <summary>
        /// Test the property 'IsoCode' 
        /// </summary>
        [Test]
        public void IsoCodeTest()
        {
            // TODO: unit test for the property 'IsoCode' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        

    }

}
