using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConferencingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConferencingInfoTests
    {
        private ConferencingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConferencingInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ConferencingInfo
        /// </summary>
        [Test]
        public void ConferencingInfoInstanceTest()
        {
            Assert.IsInstanceOf<ConferencingInfo> (instance, "instance is a ConferencingInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'AllowJoinBeforeHost' 
        /// </summary>
        [Test]
        public void AllowJoinBeforeHostTest()
        {
            // TODO: unit test for the property 'AllowJoinBeforeHost' 
        }
        
        /// <summary>
        /// Test the property 'HostCode' 
        /// </summary>
        [Test]
        public void HostCodeTest()
        {
            // TODO: unit test for the property 'HostCode' 
        }
        
        /// <summary>
        /// Test the property 'Mode' 
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO: unit test for the property 'Mode' 
        }
        
        /// <summary>
        /// Test the property 'ParticipantCode' 
        /// </summary>
        [Test]
        public void ParticipantCodeTest()
        {
            // TODO: unit test for the property 'ParticipantCode' 
        }
        
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        
        /// <summary>
        /// Test the property 'TapToJoinUri' 
        /// </summary>
        [Test]
        public void TapToJoinUriTest()
        {
            // TODO: unit test for the property 'TapToJoinUri' 
        }
        
        /// <summary>
        /// Test the property 'PhoneNumbers' 
        /// </summary>
        [Test]
        public void PhoneNumbersTest()
        {
            // TODO: unit test for the property 'PhoneNumbers' 
        }
        

    }

}
