using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeviceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceInfoTests
    {
        private DeviceInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeviceInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of DeviceInfo
        /// </summary>
        [Test]
        public void DeviceInfoInstanceTest()
        {
            Assert.IsInstanceOf<DeviceInfo> (instance, "instance is a DeviceInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Sku' 
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO: unit test for the property 'Sku' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'Serial' 
        /// </summary>
        [Test]
        public void SerialTest()
        {
            // TODO: unit test for the property 'Serial' 
        }
        
        /// <summary>
        /// Test the property 'ComputerName' 
        /// </summary>
        [Test]
        public void ComputerNameTest()
        {
            // TODO: unit test for the property 'ComputerName' 
        }
        
        /// <summary>
        /// Test the property 'Model' 
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO: unit test for the property 'Model' 
        }
        
        /// <summary>
        /// Test the property 'Extension' 
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO: unit test for the property 'Extension' 
        }
        
        /// <summary>
        /// Test the property 'EmergencyServiceAddress' 
        /// </summary>
        [Test]
        public void EmergencyServiceAddressTest()
        {
            // TODO: unit test for the property 'EmergencyServiceAddress' 
        }
        
        /// <summary>
        /// Test the property 'PhoneLines' 
        /// </summary>
        [Test]
        public void PhoneLinesTest()
        {
            // TODO: unit test for the property 'PhoneLines' 
        }
        
        /// <summary>
        /// Test the property 'Shipping' 
        /// </summary>
        [Test]
        public void ShippingTest()
        {
            // TODO: unit test for the property 'Shipping' 
        }
        
        /// <summary>
        /// Test the property 'BoxBillingId' 
        /// </summary>
        [Test]
        public void BoxBillingIdTest()
        {
            // TODO: unit test for the property 'BoxBillingId' 
        }
        

    }

}
