using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtensionInfoRequestStatusInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionInfoRequestStatusInfoTests
    {
        private ExtensionInfoRequestStatusInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExtensionInfoRequestStatusInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ExtensionInfoRequestStatusInfo
        /// </summary>
        [Test]
        public void ExtensionInfoRequestStatusInfoInstanceTest()
        {
            Assert.IsInstanceOf<ExtensionInfoRequestStatusInfo> (instance, "instance is a ExtensionInfoRequestStatusInfo");
        }

        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'StatusInfo' 
        /// </summary>
        [Test]
        public void StatusInfoTest()
        {
            // TODO: unit test for the property 'StatusInfo' 
        }
        

    }

}
