using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtensionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionInfoTests
    {
        private ExtensionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExtensionInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ExtensionInfo
        /// </summary>
        [Test]
        public void ExtensionInfoInstanceTest()
        {
            Assert.IsInstanceOf<ExtensionInfo> (instance, "instance is a ExtensionInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Contact' 
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO: unit test for the property 'Contact' 
        }
        
        /// <summary>
        /// Test the property 'Departments' 
        /// </summary>
        [Test]
        public void DepartmentsTest()
        {
            // TODO: unit test for the property 'Departments' 
        }
        
        /// <summary>
        /// Test the property 'ExtensionNumber' 
        /// </summary>
        [Test]
        public void ExtensionNumberTest()
        {
            // TODO: unit test for the property 'ExtensionNumber' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'PartnerId' 
        /// </summary>
        [Test]
        public void PartnerIdTest()
        {
            // TODO: unit test for the property 'PartnerId' 
        }
        
        /// <summary>
        /// Test the property 'Permissions' 
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO: unit test for the property 'Permissions' 
        }
        
        /// <summary>
        /// Test the property 'ProfileImage' 
        /// </summary>
        [Test]
        public void ProfileImageTest()
        {
            // TODO: unit test for the property 'ProfileImage' 
        }
        
        /// <summary>
        /// Test the property 'References' 
        /// </summary>
        [Test]
        public void ReferencesTest()
        {
            // TODO: unit test for the property 'References' 
        }
        
        /// <summary>
        /// Test the property 'RegionalSettings' 
        /// </summary>
        [Test]
        public void RegionalSettingsTest()
        {
            // TODO: unit test for the property 'RegionalSettings' 
        }
        
        /// <summary>
        /// Test the property 'ServiceFeatures' 
        /// </summary>
        [Test]
        public void ServiceFeaturesTest()
        {
            // TODO: unit test for the property 'ServiceFeatures' 
        }
        
        /// <summary>
        /// Test the property 'SetupWizardState' 
        /// </summary>
        [Test]
        public void SetupWizardStateTest()
        {
            // TODO: unit test for the property 'SetupWizardState' 
        }
        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'StatusInfo' 
        /// </summary>
        [Test]
        public void StatusInfoTest()
        {
            // TODO: unit test for the property 'StatusInfo' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        

    }

}
