using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtensionInfoRequestContactInfoRegionalSettingsTimezone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionInfoRequestContactInfoRegionalSettingsTimezoneTests
    {
        private ExtensionInfoRequestContactInfoRegionalSettingsTimezone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExtensionInfoRequestContactInfoRegionalSettingsTimezone();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ExtensionInfoRequestContactInfoRegionalSettingsTimezone
        /// </summary>
        [Test]
        public void ExtensionInfoRequestContactInfoRegionalSettingsTimezoneInstanceTest()
        {
            Assert.IsInstanceOf<ExtensionInfoRequestContactInfoRegionalSettingsTimezone> (instance, "instance is a ExtensionInfoRequestContactInfoRegionalSettingsTimezone");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        

    }

}
