using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtensionInfoRequestPasswordPIN
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionInfoRequestPasswordPINTests
    {
        private ExtensionInfoRequestPasswordPIN instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExtensionInfoRequestPasswordPIN();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ExtensionInfoRequestPasswordPIN
        /// </summary>
        [Test]
        public void ExtensionInfoRequestPasswordPINInstanceTest()
        {
            Assert.IsInstanceOf<ExtensionInfoRequestPasswordPIN> (instance, "instance is a ExtensionInfoRequestPasswordPIN");
        }

        
        /// <summary>
        /// Test the property 'Password' 
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO: unit test for the property 'Password' 
        }
        
        /// <summary>
        /// Test the property 'IvrPin' 
        /// </summary>
        [Test]
        public void IvrPinTest()
        {
            // TODO: unit test for the property 'IvrPin' 
        }
        

    }

}
