using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FullCountryInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FullCountryInfoTests
    {
        private FullCountryInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FullCountryInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of FullCountryInfo
        /// </summary>
        [Test]
        public void FullCountryInfoInstanceTest()
        {
            Assert.IsInstanceOf<FullCountryInfo> (instance, "instance is a FullCountryInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'CallingCode' 
        /// </summary>
        [Test]
        public void CallingCodeTest()
        {
            // TODO: unit test for the property 'CallingCode' 
        }
        
        /// <summary>
        /// Test the property 'EmergencyCalling' 
        /// </summary>
        [Test]
        public void EmergencyCallingTest()
        {
            // TODO: unit test for the property 'EmergencyCalling' 
        }
        
        /// <summary>
        /// Test the property 'IsoCode' 
        /// </summary>
        [Test]
        public void IsoCodeTest()
        {
            // TODO: unit test for the property 'IsoCode' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'NumberSelling' 
        /// </summary>
        [Test]
        public void NumberSellingTest()
        {
            // TODO: unit test for the property 'NumberSelling' 
        }
        
        /// <summary>
        /// Test the property 'LoginAllowed' 
        /// </summary>
        [Test]
        public void LoginAllowedTest()
        {
            // TODO: unit test for the property 'LoginAllowed' 
        }
        

    }

}
