using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GrantInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GrantInfoTests
    {
        private GrantInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new GrantInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of GrantInfo
        /// </summary>
        [Test]
        public void GrantInfoInstanceTest()
        {
            Assert.IsInstanceOf<GrantInfo> (instance, "instance is a GrantInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Extension' 
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO: unit test for the property 'Extension' 
        }
        
        /// <summary>
        /// Test the property 'CallPickup' 
        /// </summary>
        [Test]
        public void CallPickupTest()
        {
            // TODO: unit test for the property 'CallPickup' 
        }
        
        /// <summary>
        /// Test the property 'CallMonitoring' 
        /// </summary>
        [Test]
        public void CallMonitoringTest()
        {
            // TODO: unit test for the property 'CallMonitoring' 
        }
        

    }

}
