using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponseDefault13
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponseDefault13Tests
    {
        private InlineResponseDefault13 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InlineResponseDefault13();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of InlineResponseDefault13
        /// </summary>
        [Test]
        public void InlineResponseDefault13InstanceTest()
        {
            Assert.IsInstanceOf<InlineResponseDefault13> (instance, "instance is a InlineResponseDefault13");
        }

        
        /// <summary>
        /// Test the property 'Navigation' 
        /// </summary>
        [Test]
        public void NavigationTest()
        {
            // TODO: unit test for the property 'Navigation' 
        }
        
        /// <summary>
        /// Test the property 'Records' 
        /// </summary>
        [Test]
        public void RecordsTest()
        {
            // TODO: unit test for the property 'Records' 
        }
        
        /// <summary>
        /// Test the property 'Paging' 
        /// </summary>
        [Test]
        public void PagingTest()
        {
            // TODO: unit test for the property 'Paging' 
        }
        

    }

}
