using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponseDefault1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponseDefault1Tests
    {
        private InlineResponseDefault1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InlineResponseDefault1();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of InlineResponseDefault1
        /// </summary>
        [Test]
        public void InlineResponseDefault1InstanceTest()
        {
            Assert.IsInstanceOf<InlineResponseDefault1> (instance, "instance is a InlineResponseDefault1");
        }

        
        /// <summary>
        /// Test the property 'EndpointId' 
        /// </summary>
        [Test]
        public void EndpointIdTest()
        {
            // TODO: unit test for the property 'EndpointId' 
        }
        
        /// <summary>
        /// Test the property 'Scope' 
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO: unit test for the property 'Scope' 
        }
        
        /// <summary>
        /// Test the property 'OwnerId' 
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO: unit test for the property 'OwnerId' 
        }
        
        /// <summary>
        /// Test the property 'TokenType' 
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO: unit test for the property 'TokenType' 
        }
        
        /// <summary>
        /// Test the property 'ExpiresIn' 
        /// </summary>
        [Test]
        public void ExpiresInTest()
        {
            // TODO: unit test for the property 'ExpiresIn' 
        }
        
        /// <summary>
        /// Test the property 'RefreshToken' 
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO: unit test for the property 'RefreshToken' 
        }
        
        /// <summary>
        /// Test the property 'RefreshTokenExpiresIn' 
        /// </summary>
        [Test]
        public void RefreshTokenExpiresInTest()
        {
            // TODO: unit test for the property 'RefreshTokenExpiresIn' 
        }
        
        /// <summary>
        /// Test the property 'AccessToken' 
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO: unit test for the property 'AccessToken' 
        }
        

    }

}
