using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponseDefault3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponseDefault3Tests
    {
        private InlineResponseDefault3 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InlineResponseDefault3();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of InlineResponseDefault3
        /// </summary>
        [Test]
        public void InlineResponseDefault3InstanceTest()
        {
            Assert.IsInstanceOf<InlineResponseDefault3> (instance, "instance is a InlineResponseDefault3");
        }

        
        /// <summary>
        /// Test the property 'Email' 
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO: unit test for the property 'Email' 
        }
        
        /// <summary>
        /// Test the property 'Company' 
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO: unit test for the property 'Company' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'BusinessAddress' 
        /// </summary>
        [Test]
        public void BusinessAddressTest()
        {
            // TODO: unit test for the property 'BusinessAddress' 
        }
        

    }

}
