using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LanguageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LanguageInfoTests
    {
        private LanguageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LanguageInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of LanguageInfo
        /// </summary>
        [Test]
        public void LanguageInfoInstanceTest()
        {
            Assert.IsInstanceOf<LanguageInfo> (instance, "instance is a LanguageInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Greeting' 
        /// </summary>
        [Test]
        public void GreetingTest()
        {
            // TODO: unit test for the property 'Greeting' 
        }
        
        /// <summary>
        /// Test the property 'FormattingLocale' 
        /// </summary>
        [Test]
        public void FormattingLocaleTest()
        {
            // TODO: unit test for the property 'FormattingLocale' 
        }
        
        /// <summary>
        /// Test the property 'LocaleCode' 
        /// </summary>
        [Test]
        public void LocaleCodeTest()
        {
            // TODO: unit test for the property 'LocaleCode' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'Ui' 
        /// </summary>
        [Test]
        public void UiTest()
        {
            // TODO: unit test for the property 'Ui' 
        }
        

    }

}
