using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LegInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LegInfoTests
    {
        private LegInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LegInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of LegInfo
        /// </summary>
        [Test]
        public void LegInfoInstanceTest()
        {
            Assert.IsInstanceOf<LegInfo> (instance, "instance is a LegInfo");
        }

        
        /// <summary>
        /// Test the property 'Action' 
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO: unit test for the property 'Action' 
        }
        
        /// <summary>
        /// Test the property 'Direction' 
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO: unit test for the property 'Direction' 
        }
        
        /// <summary>
        /// Test the property 'Duration' 
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO: unit test for the property 'Duration' 
        }
        
        /// <summary>
        /// Test the property 'Extension' 
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO: unit test for the property 'Extension' 
        }
        
        /// <summary>
        /// Test the property 'LegType' 
        /// </summary>
        [Test]
        public void LegTypeTest()
        {
            // TODO: unit test for the property 'LegType' 
        }
        
        /// <summary>
        /// Test the property 'StartTime' 
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO: unit test for the property 'StartTime' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'Result' 
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO: unit test for the property 'Result' 
        }
        
        /// <summary>
        /// Test the property 'From' 
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO: unit test for the property 'From' 
        }
        
        /// <summary>
        /// Test the property 'To' 
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO: unit test for the property 'To' 
        }
        
        /// <summary>
        /// Test the property 'Transport' 
        /// </summary>
        [Test]
        public void TransportTest()
        {
            // TODO: unit test for the property 'Transport' 
        }
        
        /// <summary>
        /// Test the property 'Recording' 
        /// </summary>
        [Test]
        public void RecordingTest()
        {
            // TODO: unit test for the property 'Recording' 
        }
        

    }

}
