using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LookUpPhoneNumberPhoneNumberInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LookUpPhoneNumberPhoneNumberInfoTests
    {
        private LookUpPhoneNumberPhoneNumberInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LookUpPhoneNumberPhoneNumberInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of LookUpPhoneNumberPhoneNumberInfo
        /// </summary>
        [Test]
        public void LookUpPhoneNumberPhoneNumberInfoInstanceTest()
        {
            Assert.IsInstanceOf<LookUpPhoneNumberPhoneNumberInfo> (instance, "instance is a LookUpPhoneNumberPhoneNumberInfo");
        }

        
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        
        /// <summary>
        /// Test the property 'FormattedNumber' 
        /// </summary>
        [Test]
        public void FormattedNumberTest()
        {
            // TODO: unit test for the property 'FormattedNumber' 
        }
        
        /// <summary>
        /// Test the property 'VanityPattern' 
        /// </summary>
        [Test]
        public void VanityPatternTest()
        {
            // TODO: unit test for the property 'VanityPattern' 
        }
        
        /// <summary>
        /// Test the property 'Rank' 
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO: unit test for the property 'Rank' 
        }
        

    }

}
