using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageInfoTests
    {
        private MessageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MessageInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of MessageInfo
        /// </summary>
        [Test]
        public void MessageInfoInstanceTest()
        {
            Assert.IsInstanceOf<MessageInfo> (instance, "instance is a MessageInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Attachments' 
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO: unit test for the property 'Attachments' 
        }
        
        /// <summary>
        /// Test the property 'Availability' 
        /// </summary>
        [Test]
        public void AvailabilityTest()
        {
            // TODO: unit test for the property 'Availability' 
        }
        
        /// <summary>
        /// Test the property 'ConversationId' 
        /// </summary>
        [Test]
        public void ConversationIdTest()
        {
            // TODO: unit test for the property 'ConversationId' 
        }
        
        /// <summary>
        /// Test the property 'CreationTime' 
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO: unit test for the property 'CreationTime' 
        }
        
        /// <summary>
        /// Test the property 'DeliveryErrorCode' 
        /// </summary>
        [Test]
        public void DeliveryErrorCodeTest()
        {
            // TODO: unit test for the property 'DeliveryErrorCode' 
        }
        
        /// <summary>
        /// Test the property 'Direction' 
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO: unit test for the property 'Direction' 
        }
        
        /// <summary>
        /// Test the property 'FaxPageCount' 
        /// </summary>
        [Test]
        public void FaxPageCountTest()
        {
            // TODO: unit test for the property 'FaxPageCount' 
        }
        
        /// <summary>
        /// Test the property 'FaxResolution' 
        /// </summary>
        [Test]
        public void FaxResolutionTest()
        {
            // TODO: unit test for the property 'FaxResolution' 
        }
        
        /// <summary>
        /// Test the property 'From' 
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO: unit test for the property 'From' 
        }
        
        /// <summary>
        /// Test the property 'LastModifiedTime' 
        /// </summary>
        [Test]
        public void LastModifiedTimeTest()
        {
            // TODO: unit test for the property 'LastModifiedTime' 
        }
        
        /// <summary>
        /// Test the property 'MessageStatus' 
        /// </summary>
        [Test]
        public void MessageStatusTest()
        {
            // TODO: unit test for the property 'MessageStatus' 
        }
        
        /// <summary>
        /// Test the property 'PgToDepartment' 
        /// </summary>
        [Test]
        public void PgToDepartmentTest()
        {
            // TODO: unit test for the property 'PgToDepartment' 
        }
        
        /// <summary>
        /// Test the property 'Priority' 
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO: unit test for the property 'Priority' 
        }
        
        /// <summary>
        /// Test the property 'ReadStatus' 
        /// </summary>
        [Test]
        public void ReadStatusTest()
        {
            // TODO: unit test for the property 'ReadStatus' 
        }
        
        /// <summary>
        /// Test the property 'SmsDeliveryTime' 
        /// </summary>
        [Test]
        public void SmsDeliveryTimeTest()
        {
            // TODO: unit test for the property 'SmsDeliveryTime' 
        }
        
        /// <summary>
        /// Test the property 'SmsSendingAttemptsCount' 
        /// </summary>
        [Test]
        public void SmsSendingAttemptsCountTest()
        {
            // TODO: unit test for the property 'SmsSendingAttemptsCount' 
        }
        
        /// <summary>
        /// Test the property 'Subject' 
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO: unit test for the property 'Subject' 
        }
        
        /// <summary>
        /// Test the property 'To' 
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO: unit test for the property 'To' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'VmTranscriptionStatus' 
        /// </summary>
        [Test]
        public void VmTranscriptionStatusTest()
        {
            // TODO: unit test for the property 'VmTranscriptionStatus' 
        }
        

    }

}
