using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NavigationInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NavigationInfoTests
    {
        private NavigationInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NavigationInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of NavigationInfo
        /// </summary>
        [Test]
        public void NavigationInfoInstanceTest()
        {
            Assert.IsInstanceOf<NavigationInfo> (instance, "instance is a NavigationInfo");
        }

        
        /// <summary>
        /// Test the property 'FirstPage' 
        /// </summary>
        [Test]
        public void FirstPageTest()
        {
            // TODO: unit test for the property 'FirstPage' 
        }
        
        /// <summary>
        /// Test the property 'NextPage' 
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO: unit test for the property 'NextPage' 
        }
        
        /// <summary>
        /// Test the property 'PreviousPage' 
        /// </summary>
        [Test]
        public void PreviousPageTest()
        {
            // TODO: unit test for the property 'PreviousPage' 
        }
        
        /// <summary>
        /// Test the property 'LastPage' 
        /// </summary>
        [Test]
        public void LastPageTest()
        {
            // TODO: unit test for the property 'LastPage' 
        }
        

    }

}
