using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PagingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PagingInfoTests
    {
        private PagingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PagingInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PagingInfo
        /// </summary>
        [Test]
        public void PagingInfoInstanceTest()
        {
            Assert.IsInstanceOf<PagingInfo> (instance, "instance is a PagingInfo");
        }

        
        /// <summary>
        /// Test the property 'Page' 
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO: unit test for the property 'Page' 
        }
        
        /// <summary>
        /// Test the property 'PerPage' 
        /// </summary>
        [Test]
        public void PerPageTest()
        {
            // TODO: unit test for the property 'PerPage' 
        }
        
        /// <summary>
        /// Test the property 'PageStart' 
        /// </summary>
        [Test]
        public void PageStartTest()
        {
            // TODO: unit test for the property 'PageStart' 
        }
        
        /// <summary>
        /// Test the property 'PageEnd' 
        /// </summary>
        [Test]
        public void PageEndTest()
        {
            // TODO: unit test for the property 'PageEnd' 
        }
        
        /// <summary>
        /// Test the property 'TotalPages' 
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO: unit test for the property 'TotalPages' 
        }
        
        /// <summary>
        /// Test the property 'TotalElements' 
        /// </summary>
        [Test]
        public void TotalElementsTest()
        {
            // TODO: unit test for the property 'TotalElements' 
        }
        

    }

}
