using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ParsePhoneNumberPhoneNumberInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ParsePhoneNumberPhoneNumberInfoTests
    {
        private ParsePhoneNumberPhoneNumberInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ParsePhoneNumberPhoneNumberInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ParsePhoneNumberPhoneNumberInfo
        /// </summary>
        [Test]
        public void ParsePhoneNumberPhoneNumberInfoInstanceTest()
        {
            Assert.IsInstanceOf<ParsePhoneNumberPhoneNumberInfo> (instance, "instance is a ParsePhoneNumberPhoneNumberInfo");
        }

        
        /// <summary>
        /// Test the property 'AreaCode' 
        /// </summary>
        [Test]
        public void AreaCodeTest()
        {
            // TODO: unit test for the property 'AreaCode' 
        }
        
        /// <summary>
        /// Test the property 'Country' 
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO: unit test for the property 'Country' 
        }
        
        /// <summary>
        /// Test the property 'Dialable' 
        /// </summary>
        [Test]
        public void DialableTest()
        {
            // TODO: unit test for the property 'Dialable' 
        }
        
        /// <summary>
        /// Test the property 'E164' 
        /// </summary>
        [Test]
        public void E164Test()
        {
            // TODO: unit test for the property 'E164' 
        }
        
        /// <summary>
        /// Test the property 'FormattedInternational' 
        /// </summary>
        [Test]
        public void FormattedInternationalTest()
        {
            // TODO: unit test for the property 'FormattedInternational' 
        }
        
        /// <summary>
        /// Test the property 'FormattedNational' 
        /// </summary>
        [Test]
        public void FormattedNationalTest()
        {
            // TODO: unit test for the property 'FormattedNational' 
        }
        
        /// <summary>
        /// Test the property 'OriginalString' 
        /// </summary>
        [Test]
        public void OriginalStringTest()
        {
            // TODO: unit test for the property 'OriginalString' 
        }
        
        /// <summary>
        /// Test the property 'Special' 
        /// </summary>
        [Test]
        public void SpecialTest()
        {
            // TODO: unit test for the property 'Special' 
        }
        
        /// <summary>
        /// Test the property 'Normalized' 
        /// </summary>
        [Test]
        public void NormalizedTest()
        {
            // TODO: unit test for the property 'Normalized' 
        }
        

    }

}
