using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PhoneNumberInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PhoneNumberInfoTests
    {
        private PhoneNumberInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PhoneNumberInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PhoneNumberInfo
        /// </summary>
        [Test]
        public void PhoneNumberInfoInstanceTest()
        {
            Assert.IsInstanceOf<PhoneNumberInfo> (instance, "instance is a PhoneNumberInfo");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Country' 
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO: unit test for the property 'Country' 
        }
        
        /// <summary>
        /// Test the property 'Extension' 
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO: unit test for the property 'Extension' 
        }
        
        /// <summary>
        /// Test the property 'Features' 
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO: unit test for the property 'Features' 
        }
        
        /// <summary>
        /// Test the property 'Location' 
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO: unit test for the property 'Location' 
        }
        
        /// <summary>
        /// Test the property 'PaymentType' 
        /// </summary>
        [Test]
        public void PaymentTypeTest()
        {
            // TODO: unit test for the property 'PaymentType' 
        }
        
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'UsageType' 
        /// </summary>
        [Test]
        public void UsageTypeTest()
        {
            // TODO: unit test for the property 'UsageType' 
        }
        

    }

}
