using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProfileImageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProfileImageInfoTests
    {
        private ProfileImageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProfileImageInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ProfileImageInfo
        /// </summary>
        [Test]
        public void ProfileImageInfoInstanceTest()
        {
            Assert.IsInstanceOf<ProfileImageInfo> (instance, "instance is a ProfileImageInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'Etag' 
        /// </summary>
        [Test]
        public void EtagTest()
        {
            // TODO: unit test for the property 'Etag' 
        }
        
        /// <summary>
        /// Test the property 'LastModified' 
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO: unit test for the property 'LastModified' 
        }
        
        /// <summary>
        /// Test the property 'ContentType' 
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO: unit test for the property 'ContentType' 
        }
        
        /// <summary>
        /// Test the property 'Scales' 
        /// </summary>
        [Test]
        public void ScalesTest()
        {
            // TODO: unit test for the property 'Scales' 
        }
        

    }

}
