using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RegionalSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegionalSettingsTests
    {
        private RegionalSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RegionalSettings();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of RegionalSettings
        /// </summary>
        [Test]
        public void RegionalSettingsInstanceTest()
        {
            Assert.IsInstanceOf<RegionalSettings> (instance, "instance is a RegionalSettings");
        }

        
        /// <summary>
        /// Test the property 'HomeCountry' 
        /// </summary>
        [Test]
        public void HomeCountryTest()
        {
            // TODO: unit test for the property 'HomeCountry' 
        }
        
        /// <summary>
        /// Test the property 'Timezone' 
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO: unit test for the property 'Timezone' 
        }
        
        /// <summary>
        /// Test the property 'Language' 
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO: unit test for the property 'Language' 
        }
        
        /// <summary>
        /// Test the property 'GreetingLanguage' 
        /// </summary>
        [Test]
        public void GreetingLanguageTest()
        {
            // TODO: unit test for the property 'GreetingLanguage' 
        }
        
        /// <summary>
        /// Test the property 'FormattingLocale' 
        /// </summary>
        [Test]
        public void FormattingLocaleTest()
        {
            // TODO: unit test for the property 'FormattingLocale' 
        }
        

    }

}
