using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RingOutStatusInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RingOutStatusInfoTests
    {
        private RingOutStatusInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RingOutStatusInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of RingOutStatusInfo
        /// </summary>
        [Test]
        public void RingOutStatusInfoInstanceTest()
        {
            Assert.IsInstanceOf<RingOutStatusInfo> (instance, "instance is a RingOutStatusInfo");
        }

        
        /// <summary>
        /// Test the property 'CallStatus' 
        /// </summary>
        [Test]
        public void CallStatusTest()
        {
            // TODO: unit test for the property 'CallStatus' 
        }
        
        /// <summary>
        /// Test the property 'CallerStatus' 
        /// </summary>
        [Test]
        public void CallerStatusTest()
        {
            // TODO: unit test for the property 'CallerStatus' 
        }
        
        /// <summary>
        /// Test the property 'CalleeStatus' 
        /// </summary>
        [Test]
        public void CalleeStatusTest()
        {
            // TODO: unit test for the property 'CalleeStatus' 
        }
        

    }

}
