using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RuleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleInfoTests
    {
        private RuleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RuleInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of RuleInfo
        /// </summary>
        [Test]
        public void RuleInfoInstanceTest()
        {
            Assert.IsInstanceOf<RuleInfo> (instance, "instance is a RuleInfo");
        }

        
        /// <summary>
        /// Test the property 'Index' 
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO: unit test for the property 'Index' 
        }
        
        /// <summary>
        /// Test the property 'RingCount' 
        /// </summary>
        [Test]
        public void RingCountTest()
        {
            // TODO: unit test for the property 'RingCount' 
        }
        
        /// <summary>
        /// Test the property 'ForwardingNumbers' 
        /// </summary>
        [Test]
        public void ForwardingNumbersTest()
        {
            // TODO: unit test for the property 'ForwardingNumbers' 
        }
        

    }

}
