using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScheduleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduleInfoTests
    {
        private ScheduleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ScheduleInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ScheduleInfo
        /// </summary>
        [Test]
        public void ScheduleInfoInstanceTest()
        {
            Assert.IsInstanceOf<ScheduleInfo> (instance, "instance is a ScheduleInfo");
        }

        
        /// <summary>
        /// Test the property 'WeeklyRanges' 
        /// </summary>
        [Test]
        public void WeeklyRangesTest()
        {
            // TODO: unit test for the property 'WeeklyRanges' 
        }
        
        /// <summary>
        /// Test the property 'Ranges' 
        /// </summary>
        [Test]
        public void RangesTest()
        {
            // TODO: unit test for the property 'Ranges' 
        }
        
        /// <summary>
        /// Test the property '_Ref' 
        /// </summary>
        [Test]
        public void _RefTest()
        {
            // TODO: unit test for the property '_Ref' 
        }
        

    }

}
