using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceFeatureInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceFeatureInfoTests
    {
        private ServiceFeatureInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ServiceFeatureInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ServiceFeatureInfo
        /// </summary>
        [Test]
        public void ServiceFeatureInfoInstanceTest()
        {
            Assert.IsInstanceOf<ServiceFeatureInfo> (instance, "instance is a ServiceFeatureInfo");
        }

        
        /// <summary>
        /// Test the property 'FeatureName' 
        /// </summary>
        [Test]
        public void FeatureNameTest()
        {
            // TODO: unit test for the property 'FeatureName' 
        }
        
        /// <summary>
        /// Test the property 'Enabled' 
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO: unit test for the property 'Enabled' 
        }
        

    }

}
