using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceInfoTests
    {
        private ServiceInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ServiceInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ServiceInfo
        /// </summary>
        [Test]
        public void ServiceInfoInstanceTest()
        {
            Assert.IsInstanceOf<ServiceInfo> (instance, "instance is a ServiceInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'BillingPlan' 
        /// </summary>
        [Test]
        public void BillingPlanTest()
        {
            // TODO: unit test for the property 'BillingPlan' 
        }
        
        /// <summary>
        /// Test the property 'Brand' 
        /// </summary>
        [Test]
        public void BrandTest()
        {
            // TODO: unit test for the property 'Brand' 
        }
        
        /// <summary>
        /// Test the property 'ServicePlan' 
        /// </summary>
        [Test]
        public void ServicePlanTest()
        {
            // TODO: unit test for the property 'ServicePlan' 
        }
        
        /// <summary>
        /// Test the property 'TargetServicePlan' 
        /// </summary>
        [Test]
        public void TargetServicePlanTest()
        {
            // TODO: unit test for the property 'TargetServicePlan' 
        }
        

    }

}
