using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShippingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShippingInfoTests
    {
        private ShippingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ShippingInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ShippingInfo
        /// </summary>
        [Test]
        public void ShippingInfoInstanceTest()
        {
            Assert.IsInstanceOf<ShippingInfo> (instance, "instance is a ShippingInfo");
        }

        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'Carrier' 
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO: unit test for the property 'Carrier' 
        }
        
        /// <summary>
        /// Test the property 'TrackingNumber' 
        /// </summary>
        [Test]
        public void TrackingNumberTest()
        {
            // TODO: unit test for the property 'TrackingNumber' 
        }
        
        /// <summary>
        /// Test the property 'Method' 
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO: unit test for the property 'Method' 
        }
        
        /// <summary>
        /// Test the property 'Address' 
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO: unit test for the property 'Address' 
        }
        

    }

}
