using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubscriptionRequestDeliveryMode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionRequestDeliveryModeTests
    {
        private SubscriptionRequestDeliveryMode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SubscriptionRequestDeliveryMode();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of SubscriptionRequestDeliveryMode
        /// </summary>
        [Test]
        public void SubscriptionRequestDeliveryModeInstanceTest()
        {
            Assert.IsInstanceOf<SubscriptionRequestDeliveryMode> (instance, "instance is a SubscriptionRequestDeliveryMode");
        }

        
        /// <summary>
        /// Test the property 'TransportType' 
        /// </summary>
        [Test]
        public void TransportTypeTest()
        {
            // TODO: unit test for the property 'TransportType' 
        }
        
        /// <summary>
        /// Test the property 'Encryption' 
        /// </summary>
        [Test]
        public void EncryptionTest()
        {
            // TODO: unit test for the property 'Encryption' 
        }
        

    }

}
