using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SyncInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SyncInfoTests
    {
        private SyncInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SyncInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of SyncInfo
        /// </summary>
        [Test]
        public void SyncInfoInstanceTest()
        {
            Assert.IsInstanceOf<SyncInfo> (instance, "instance is a SyncInfo");
        }

        
        /// <summary>
        /// Test the property 'SyncType' 
        /// </summary>
        [Test]
        public void SyncTypeTest()
        {
            // TODO: unit test for the property 'SyncType' 
        }
        
        /// <summary>
        /// Test the property 'SyncToken' 
        /// </summary>
        [Test]
        public void SyncTokenTest()
        {
            // TODO: unit test for the property 'SyncToken' 
        }
        
        /// <summary>
        /// Test the property 'SyncTime' 
        /// </summary>
        [Test]
        public void SyncTimeTest()
        {
            // TODO: unit test for the property 'SyncTime' 
        }
        

    }

}
