using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VersionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VersionInfoTests
    {
        private VersionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VersionInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of VersionInfo
        /// </summary>
        [Test]
        public void VersionInfoInstanceTest()
        {
            Assert.IsInstanceOf<VersionInfo> (instance, "instance is a VersionInfo");
        }

        
        /// <summary>
        /// Test the property 'Uri' 
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO: unit test for the property 'Uri' 
        }
        
        /// <summary>
        /// Test the property 'VersionString' 
        /// </summary>
        [Test]
        public void VersionStringTest()
        {
            // TODO: unit test for the property 'VersionString' 
        }
        
        /// <summary>
        /// Test the property 'ReleaseDate' 
        /// </summary>
        [Test]
        public void ReleaseDateTest()
        {
            // TODO: unit test for the property 'ReleaseDate' 
        }
        
        /// <summary>
        /// Test the property 'UriString' 
        /// </summary>
        [Test]
        public void UriStringTest()
        {
            // TODO: unit test for the property 'UriString' 
        }
        

    }

}
