using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WeeklyScheduleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WeeklyScheduleInfoTests
    {
        private WeeklyScheduleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WeeklyScheduleInfo();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of WeeklyScheduleInfo
        /// </summary>
        [Test]
        public void WeeklyScheduleInfoInstanceTest()
        {
            Assert.IsInstanceOf<WeeklyScheduleInfo> (instance, "instance is a WeeklyScheduleInfo");
        }

        
        /// <summary>
        /// Test the property 'Monday' 
        /// </summary>
        [Test]
        public void MondayTest()
        {
            // TODO: unit test for the property 'Monday' 
        }
        
        /// <summary>
        /// Test the property 'Tuesday' 
        /// </summary>
        [Test]
        public void TuesdayTest()
        {
            // TODO: unit test for the property 'Tuesday' 
        }
        
        /// <summary>
        /// Test the property 'Wednesday' 
        /// </summary>
        [Test]
        public void WednesdayTest()
        {
            // TODO: unit test for the property 'Wednesday' 
        }
        
        /// <summary>
        /// Test the property 'Thursday' 
        /// </summary>
        [Test]
        public void ThursdayTest()
        {
            // TODO: unit test for the property 'Thursday' 
        }
        
        /// <summary>
        /// Test the property 'Friday' 
        /// </summary>
        [Test]
        public void FridayTest()
        {
            // TODO: unit test for the property 'Friday' 
        }
        
        /// <summary>
        /// Test the property 'Saturday' 
        /// </summary>
        [Test]
        public void SaturdayTest()
        {
            // TODO: unit test for the property 'Saturday' 
        }
        
        /// <summary>
        /// Test the property 'Sunday' 
        /// </summary>
        [Test]
        public void SundayTest()
        {
            // TODO: unit test for the property 'Sunday' 
        }
        

    }

}
