using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefault1 :  IEquatable<InlineResponseDefault1>
    { 
    
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault1" /> class.
        /// Initializes a new instance of the <see cref="InlineResponseDefault1" />class.
        /// </summary>
        /// <param name="EndpointId">Unique identifier of a client application passed by the client, or auto-generated by server if not specified in request.</param>
        /// <param name="Scope">List of permissions allowed with this access token, white-space separated.</param>
        /// <param name="OwnerId">Extension identifier.</param>
        /// <param name="TokenType">Type of token. Use this parameter in Authorization header of requests.</param>
        /// <param name="ExpiresIn">Issued access token TTL (time to live), in seconds.</param>
        /// <param name="RefreshToken">Refresh token to get a new access token, when the issued one expires.</param>
        /// <param name="RefreshTokenExpiresIn">Issued refresh token TTL (time to live), in seconds.</param>
        /// <param name="AccessToken">Access token to pass to subsequent API requests.</param>

        public InlineResponseDefault1(string EndpointId = null, string Scope = null, string OwnerId = null, string TokenType = null, int? ExpiresIn = null, string RefreshToken = null, int? RefreshTokenExpiresIn = null, string AccessToken = null)
        {
            this.EndpointId = EndpointId;
            this.Scope = Scope;
            this.OwnerId = OwnerId;
            this.TokenType = TokenType;
            this.ExpiresIn = ExpiresIn;
            this.RefreshToken = RefreshToken;
            this.RefreshTokenExpiresIn = RefreshTokenExpiresIn;
            this.AccessToken = AccessToken;
            
        }
        
    
        /// <summary>
        /// Unique identifier of a client application passed by the client, or auto-generated by server if not specified in request
        /// </summary>
        /// <value>Unique identifier of a client application passed by the client, or auto-generated by server if not specified in request</value>
        [DataMember(Name="endpoint_id", EmitDefaultValue=false)]
        public string EndpointId { get; set; }
    
        /// <summary>
        /// List of permissions allowed with this access token, white-space separated
        /// </summary>
        /// <value>List of permissions allowed with this access token, white-space separated</value>
        [DataMember(Name="scope", EmitDefaultValue=false)]
        public string Scope { get; set; }
    
        /// <summary>
        /// Extension identifier
        /// </summary>
        /// <value>Extension identifier</value>
        [DataMember(Name="owner_id", EmitDefaultValue=false)]
        public string OwnerId { get; set; }
    
        /// <summary>
        /// Type of token. Use this parameter in Authorization header of requests
        /// </summary>
        /// <value>Type of token. Use this parameter in Authorization header of requests</value>
        [DataMember(Name="token_type", EmitDefaultValue=false)]
        public string TokenType { get; set; }
    
        /// <summary>
        /// Issued access token TTL (time to live), in seconds
        /// </summary>
        /// <value>Issued access token TTL (time to live), in seconds</value>
        [DataMember(Name="expires_in", EmitDefaultValue=false)]
        public int? ExpiresIn { get; set; }
    
        /// <summary>
        /// Refresh token to get a new access token, when the issued one expires
        /// </summary>
        /// <value>Refresh token to get a new access token, when the issued one expires</value>
        [DataMember(Name="refresh_token", EmitDefaultValue=false)]
        public string RefreshToken { get; set; }
    
        /// <summary>
        /// Issued refresh token TTL (time to live), in seconds
        /// </summary>
        /// <value>Issued refresh token TTL (time to live), in seconds</value>
        [DataMember(Name="refresh_token_expires_in", EmitDefaultValue=false)]
        public int? RefreshTokenExpiresIn { get; set; }
    
        /// <summary>
        /// Access token to pass to subsequent API requests
        /// </summary>
        /// <value>Access token to pass to subsequent API requests</value>
        [DataMember(Name="access_token", EmitDefaultValue=false)]
        public string AccessToken { get; set; }
    
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault1 {\n");
            sb.Append("  EndpointId: ").Append(EndpointId).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  TokenType: ").Append(TokenType).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  RefreshToken: ").Append(RefreshToken).Append("\n");
            sb.Append("  RefreshTokenExpiresIn: ").Append(RefreshTokenExpiresIn).Append("\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponseDefault1);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault1 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault1 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.EndpointId == other.EndpointId ||
                    this.EndpointId != null &&
                    this.EndpointId.Equals(other.EndpointId)
                ) && 
                (
                    this.Scope == other.Scope ||
                    this.Scope != null &&
                    this.Scope.Equals(other.Scope)
                ) && 
                (
                    this.OwnerId == other.OwnerId ||
                    this.OwnerId != null &&
                    this.OwnerId.Equals(other.OwnerId)
                ) && 
                (
                    this.TokenType == other.TokenType ||
                    this.TokenType != null &&
                    this.TokenType.Equals(other.TokenType)
                ) && 
                (
                    this.ExpiresIn == other.ExpiresIn ||
                    this.ExpiresIn != null &&
                    this.ExpiresIn.Equals(other.ExpiresIn)
                ) && 
                (
                    this.RefreshToken == other.RefreshToken ||
                    this.RefreshToken != null &&
                    this.RefreshToken.Equals(other.RefreshToken)
                ) && 
                (
                    this.RefreshTokenExpiresIn == other.RefreshTokenExpiresIn ||
                    this.RefreshTokenExpiresIn != null &&
                    this.RefreshTokenExpiresIn.Equals(other.RefreshTokenExpiresIn)
                ) && 
                (
                    this.AccessToken == other.AccessToken ||
                    this.AccessToken != null &&
                    this.AccessToken.Equals(other.AccessToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                
                if (this.EndpointId != null)
                    hash = hash * 59 + this.EndpointId.GetHashCode();
                
                if (this.Scope != null)
                    hash = hash * 59 + this.Scope.GetHashCode();
                
                if (this.OwnerId != null)
                    hash = hash * 59 + this.OwnerId.GetHashCode();
                
                if (this.TokenType != null)
                    hash = hash * 59 + this.TokenType.GetHashCode();
                
                if (this.ExpiresIn != null)
                    hash = hash * 59 + this.ExpiresIn.GetHashCode();
                
                if (this.RefreshToken != null)
                    hash = hash * 59 + this.RefreshToken.GetHashCode();
                
                if (this.RefreshTokenExpiresIn != null)
                    hash = hash * 59 + this.RefreshTokenExpiresIn.GetHashCode();
                
                if (this.AccessToken != null)
                    hash = hash * 59 + this.AccessToken.GetHashCode();
                
                return hash;
            }
        }

    }
}
